from DenseNet121_model import DenseNet121_imagenet, DenseNet121_sinpesos
from DenseNet169_model import DenseNet169_imagenet, DenseNet169_sinpesos
from DenseNet201_model import DenseNet201_imagenet, DenseNet201_sinpesos
from InceptionResNetV2_model import InceptionResNetV2_imagenet, \
	InceptionResNetV2_sinpesos
from InceptionV3_model import InceptionV3_imagenet, InceptionV3_sinpesos
from MobileNet_model import MobileNet_imagenet, MobileNet_sinpesos
from ResNet50_model import ResNet50_sinpesos, ResNet50_imagenet
from VGG16_model import VGG16_imagenet, VGG16_sinpesos
from VGG19_model import VGG19_imagenet, VGG19_sinpesos
from Xception_model import Xception_imagenet, Xception_sinpesos
from InceptionV4_model import InceptionV4_imagenet, InceptionV4_sinpesos

from NASNetMobile_model import NASNetMobile_imagenet, NASNetMobile_sinpesos
